// Self-contained onboarding copy in every supported language. Kept out of the
// main i18n dictionary so the flow's strings stay together and reviewable.
// English is the source; each locale supplies a full set. Missing keys fall
// back to English via the spread in `oc()`.
import type { Lang } from "../i18n/translations";

export interface OnboardingCopy {
  langTitle: string;
  langSub: string;
  welcomeTitle: string;
  welcomeSub: string;
  feat1T: string;
  feat1D: string;
  feat2T: string;
  feat2D: string;
  feat3T: string;
  feat3D: string;
  welcomeCta: string;
  welcomeSkip: string;
  cont: string;
  skip: string;
  skipAdd: string;
  assetsTitle: string;
  assetsSub: string;
  aFutures: string;
  aForex: string;
  aStocks: string;
  aOptions: string;
  aCrypto: string;
  styleTitle: string;
  styleSub: string;
  sScalper: string;
  sScalperD: string;
  sDay: string;
  sDayD: string;
  sSwing: string;
  sSwingD: string;
  sPos: string;
  sPosD: string;
  ictTitle: string;
  ictSub: string;
  ictYes: string;
  ictNo: string;
  expTitle: string;
  expSub: string;
  eNew: string;
  eNewD: string;
  eInt: string;
  eIntD: string;
  eSea: string;
  eSeaD: string;
  eFund: string;
  eFundD: string;
  goalTitle: string;
  goalSub: string;
  gCons: string;
  gConsD: string;
  gProp: string;
  gPropD: string;
  gFull: string;
  gFullD: string;
  gSide: string;
  gSideD: string;
  gDisc: string;
  gDiscD: string;
  painTitle: string;
  painSub: string;
  pCons: string;
  pConsD: string;
  pEmo: string;
  pEmoD: string;
  pRisk: string;
  pRiskD: string;
  pJour: string;
  pJourD: string;
  pOver: string;
  pOverD: string;
  brokersTitle: string;
  brokersSub: string;
  revealTitle: string;
  revealJournal: string;
  revealPain: string;
  revealIct: string;
  revealLang: string;
  revealBrokers: string;
  revealCta: string;
  revealSaving: string;
  yourMarkets: string;
  missionCons: string;
  missionProp: string;
  missionFull: string;
  missionSide: string;
  missionDisc: string;
  // Quick-start step (optional per locale — falls back to English via oc()).
  startTitle?: string;
  startSub?: string;
  startImport?: string;
  startImportD?: string;
  startDemo?: string;
  startDemoD?: string;
  startFresh?: string;
  startWorking?: string;
  // Profile step Q3 — realistic monthly target (optional per locale).
  targetTitle?: string;
  targetSub?: string;
}

const en: OnboardingCopy = {
  langTitle: "Choose your language",
  langSub: "The whole app will be in this language.",
  welcomeTitle: "Welcome to TradeVault",
  welcomeSub:
    "Your trading journal, built to find your edge. Log every trade, see what's actually working, and fix the leaks before they cost you.",
  feat1T: "Journal every trade",
  feat1D: "Entries, exits, screenshots, mistakes — one clean log.",
  feat2T: "See your real edge",
  feat2D: "Win rate, R-multiples, and analytics that don't lie.",
  feat3T: "AI insights + checklist",
  feat3D: "Spot patterns and lock in your process before the bell.",
  welcomeCta: "Set it up — takes 30 seconds",
  welcomeSkip: "Skip, I'll explore on my own",
  cont: "Continue",
  skip: "Skip",
  skipAdd: "Skip, I'll add later",
  assetsTitle: "What do you trade?",
  assetsSub: "Pick all that apply. We'll talk in your units.",
  aFutures: "Futures",
  aForex: "Forex",
  aStocks: "Stocks",
  aOptions: "Options",
  aCrypto: "Crypto",
  styleTitle: "How do you trade it?",
  styleSub: "Your bread and butter.",
  sScalper: "Scalper",
  sScalperD: "In and out. Seconds to minutes.",
  sDay: "Day Trader",
  sDayD: "Flat by the close. No overnight risk.",
  sSwing: "Swing",
  sSwingD: "Days to weeks. Riding the bigger move.",
  sPos: "Position",
  sPosD: "Weeks to months. Macro conviction.",
  ictTitle: "Do you trade ICT / SMC concepts?",
  ictSub: "Order blocks, liquidity, FVGs, killzones.",
  ictYes: "Yes, that's me",
  ictNo: "Not really",
  expTitle: "How long you been at this?",
  expSub: "No judgment — this just tunes what we show you.",
  eNew: "Just started",
  eNewD: "Under a year",
  eInt: "Getting reps in",
  eIntD: "1–3 years",
  eSea: "Seasoned",
  eSeaD: "3 years+",
  eFund: "Funded / Prop",
  eFundD: "Trading allocated capital",
  goalTitle: "What's the mission right now?",
  goalSub: "The real reason you opened this journal.",
  gCons: "Get consistent",
  gConsD: "Stop giving back the winners.",
  gProp: "Pass a prop challenge",
  gPropD: "Hit the target, respect the rules.",
  gFull: "Go full-time",
  gFullD: "Replace the paycheck.",
  gSide: "Side income",
  gSideD: "Stack extra, low stress.",
  gDisc: "Build discipline",
  gDiscD: "Master the mind, not just the charts.",
  painTitle: "What's costing you the most?",
  painSub: "Be honest — this is where we start.",
  pCons: "Consistency",
  pConsD: "Green week, red week, repeat.",
  pEmo: "Emotional control",
  pEmoD: "Revenge trades, FOMO, tilt.",
  pRisk: "Risk management",
  pRiskD: "One trade wrecks the month.",
  pJour: "Journaling",
  pJourD: "I don't log, so I don't learn.",
  pOver: "Overtrading",
  pOverD: "Can't sit on my hands.",
  brokersTitle: "Where do you execute?",
  brokersSub: "For one-tap CSV import later. No login now — just the name.",
  revealTitle: "Your vault's ready.",
  revealJournal: "Journal set up for {assets}",
  revealPain: "We'll start with your biggest leak: {pain}",
  revealIct: "ICT / SMC confluence checklist loaded",
  revealLang: "Language set to {lang}",
  revealBrokers: "{brokers} import ready in Settings",
  revealCta: "Enter TradeVault →",
  revealSaving: "Setting up…",
  yourMarkets: "your markets",
  missionCons: "On a mission for consistency.",
  missionProp: "Chasing the payout.",
  missionFull: "Going full-time.",
  missionSide: "Stacking on the side.",
  missionDisc: "Building discipline.",
  startTitle: "Fill your vault in seconds",
  startSub: "Your dashboard and analytics come alive with your first trades.",
  startImport: "Import my trades (CSV)",
  startImportD:
    "Bring your history from your broker or another journal — the fastest way to see your real edge.",
  startDemo: "Show me a demo",
  startDemoD:
    "We drop in 3 realistic sample trades (marked “Example”) so you can explore everything instantly.",
  startFresh: "Start from zero — I'll log my first trade myself",
  startWorking: "Preparing your vault…",
  targetTitle: "Realistic monthly target?",
  targetSub: "In % — it anchors your daily checklist. Honest beats heroic.",
};

const fr: OnboardingCopy = {
  langTitle: "Choisis ta langue",
  langSub: "Toute l'application sera dans cette langue.",
  welcomeTitle: "Bienvenue sur TradeVault",
  welcomeSub:
    "Ton journal de trading, pensé pour trouver ton edge. Note chaque trade, vois ce qui marche vraiment, et corrige les fuites avant qu'elles ne coûtent cher.",
  feat1T: "Journalise chaque trade",
  feat1D: "Entrées, sorties, captures, erreurs — un seul journal clair.",
  feat2T: "Vois ton vrai edge",
  feat2D: "Taux de réussite, R-multiples et analyses qui ne mentent pas.",
  feat3T: "Insights IA + checklist",
  feat3D: "Repère les patterns et verrouille ton process avant l'ouverture.",
  welcomeCta: "Configurer — 30 secondes",
  welcomeSkip: "Passer, je découvre seul",
  cont: "Continuer",
  skip: "Passer",
  skipAdd: "Passer, j'ajouterai plus tard",
  assetsTitle: "Que trades-tu ?",
  assetsSub: "Choisis tout ce qui s'applique. On parlera dans tes unités.",
  aFutures: "Futures",
  aForex: "Forex",
  aStocks: "Actions",
  aOptions: "Options",
  aCrypto: "Crypto",
  styleTitle: "Comment tu les trades ?",
  styleSub: "Ton pain quotidien.",
  sScalper: "Scalpeur",
  sScalperD: "Dedans, dehors. Secondes à minutes.",
  sDay: "Day Trader",
  sDayD: "À plat à la clôture. Pas de risque overnight.",
  sSwing: "Swing",
  sSwingD: "Jours à semaines. Sur le mouvement de fond.",
  sPos: "Position",
  sPosD: "Semaines à mois. Conviction macro.",
  ictTitle: "Tu trades les concepts ICT / SMC ?",
  ictSub: "Order blocks, liquidité, FVG, killzones.",
  ictYes: "Oui, c'est moi",
  ictNo: "Pas vraiment",
  expTitle: "Depuis combien de temps ?",
  expSub: "Aucun jugement — ça ajuste juste ce qu'on t'affiche.",
  eNew: "Je débute",
  eNewD: "Moins d'un an",
  eInt: "Je prends du volume",
  eIntD: "1 à 3 ans",
  eSea: "Aguerri",
  eSeaD: "3 ans et plus",
  eFund: "Financé / Prop",
  eFundD: "Je trade un capital alloué",
  goalTitle: "C'est quoi la mission là ?",
  goalSub: "La vraie raison qui t'a fait ouvrir ce journal.",
  gCons: "Devenir régulier",
  gConsD: "Arrêter de rendre les gains.",
  gProp: "Passer un challenge prop",
  gPropD: "Atteindre l'objectif, respecter les règles.",
  gFull: "Passer à plein temps",
  gFullD: "Remplacer le salaire.",
  gSide: "Revenu d'appoint",
  gSideD: "Un plus, sans stress.",
  gDisc: "Construire la discipline",
  gDiscD: "Maîtriser le mental, pas que les charts.",
  painTitle: "Qu'est-ce qui te coûte le plus ?",
  painSub: "Sois honnête — c'est notre point de départ.",
  pCons: "Régularité",
  pConsD: "Semaine verte, semaine rouge, en boucle.",
  pEmo: "Contrôle émotionnel",
  pEmoD: "Revenge trades, FOMO, tilt.",
  pRisk: "Gestion du risque",
  pRiskD: "Un trade flingue le mois.",
  pJour: "Tenue du journal",
  pJourD: "Je ne note pas, donc je n'apprends pas.",
  pOver: "Surtrading",
  pOverD: "Impossible de rester les mains dans les poches.",
  brokersTitle: "Où exécutes-tu ?",
  brokersSub: "Pour l'import CSV en un clic plus tard. Pas de login — juste le nom.",
  revealTitle: "Ton vault est prêt.",
  revealJournal: "Journal configuré pour {assets}",
  revealPain: "On commence par ta plus grosse fuite : {pain}",
  revealIct: "Checklist de confluences ICT / SMC chargée",
  revealLang: "Langue réglée sur {lang}",
  revealBrokers: "Import {brokers} prêt dans les Réglages",
  revealCta: "Entrer dans TradeVault →",
  revealSaving: "Configuration…",
  yourMarkets: "tes marchés",
  missionCons: "En mission pour la régularité.",
  missionProp: "À la chasse au payout.",
  missionFull: "Direction plein temps.",
  missionSide: "Un revenu en plus.",
  missionDisc: "Construire la discipline.",
  startTitle: "Remplis ton vault en quelques secondes",
  startSub: "Ton dashboard et tes analytics prennent vie avec tes premiers trades.",
  startImport: "Importer mes trades (CSV)",
  startImportD:
    "Récupère ton historique depuis ton broker ou un autre journal — le moyen le plus rapide de voir ton vrai edge.",
  startDemo: "Voir une démo",
  startDemoD:
    "On insère 3 trades d'exemple réalistes (marqués « Exemple ») pour tout explorer instantanément.",
  startFresh: "Partir de zéro — je note mon premier trade moi-même",
  startWorking: "Préparation de ton vault…",
  targetTitle: "Objectif mensuel réaliste ?",
  targetSub: "En % — il ancre ta checklist quotidienne. Honnête vaut mieux qu'héroïque.",
};

const es: OnboardingCopy = {
  langTitle: "Elige tu idioma",
  langSub: "Toda la app estará en este idioma.",
  welcomeTitle: "Bienvenido a TradeVault",
  welcomeSub:
    "Tu diario de trading, hecho para encontrar tu edge. Registra cada operación, ve qué funciona de verdad y corrige las fugas antes de que te cuesten.",
  feat1T: "Registra cada operación",
  feat1D: "Entradas, salidas, capturas, errores — un diario limpio.",
  feat2T: "Ve tu edge real",
  feat2D: "Win rate, R-múltiples y analíticas que no mienten.",
  feat3T: "Insights de IA + checklist",
  feat3D: "Detecta patrones y fija tu proceso antes de la apertura.",
  welcomeCta: "Configurar — 30 segundos",
  welcomeSkip: "Omitir, exploro por mi cuenta",
  cont: "Continuar",
  skip: "Omitir",
  skipAdd: "Omitir, lo añado luego",
  assetsTitle: "¿Qué operas?",
  assetsSub: "Elige todo lo que aplique. Hablaremos en tus unidades.",
  aFutures: "Futuros",
  aForex: "Forex",
  aStocks: "Acciones",
  aOptions: "Opciones",
  aCrypto: "Cripto",
  styleTitle: "¿Cómo lo operas?",
  styleSub: "Tu pan de cada día.",
  sScalper: "Scalper",
  sScalperD: "Dentro y fuera. Segundos a minutos.",
  sDay: "Day Trader",
  sDayD: "Plano al cierre. Sin riesgo overnight.",
  sSwing: "Swing",
  sSwingD: "Días a semanas. Al movimiento mayor.",
  sPos: "Posición",
  sPosD: "Semanas a meses. Convicción macro.",
  ictTitle: "¿Operas conceptos ICT / SMC?",
  ictSub: "Order blocks, liquidez, FVG, killzones.",
  ictYes: "Sí, soy yo",
  ictNo: "La verdad no",
  expTitle: "¿Cuánto llevas en esto?",
  expSub: "Sin juicios — solo ajusta lo que te mostramos.",
  eNew: "Recién empiezo",
  eNewD: "Menos de un año",
  eInt: "Agarrando ritmo",
  eIntD: "1 a 3 años",
  eSea: "Con experiencia",
  eSeaD: "3 años o más",
  eFund: "Fondeado / Prop",
  eFundD: "Opero capital asignado",
  goalTitle: "¿Cuál es la misión ahora?",
  goalSub: "La verdadera razón por la que abriste este diario.",
  gCons: "Ser consistente",
  gConsD: "Dejar de devolver las ganancias.",
  gProp: "Pasar un challenge prop",
  gPropD: "Llegar al objetivo, respetar las reglas.",
  gFull: "Vivir de esto",
  gFullD: "Reemplazar el sueldo.",
  gSide: "Ingreso extra",
  gSideD: "Sumar algo, sin estrés.",
  gDisc: "Construir disciplina",
  gDiscD: "Dominar la mente, no solo los charts.",
  painTitle: "¿Qué es lo que más te cuesta?",
  painSub: "Sé honesto — aquí es donde empezamos.",
  pCons: "Consistencia",
  pConsD: "Semana verde, semana roja, repetir.",
  pEmo: "Control emocional",
  pEmoD: "Revenge trades, FOMO, tilt.",
  pRisk: "Gestión del riesgo",
  pRiskD: "Una operación arruina el mes.",
  pJour: "Llevar el diario",
  pJourD: "No registro, así que no aprendo.",
  pOver: "Sobreoperar",
  pOverD: "No puedo quedarme quieto.",
  brokersTitle: "¿Dónde ejecutas?",
  brokersSub: "Para importar CSV en un toque luego. Sin login — solo el nombre.",
  revealTitle: "Tu vault está listo.",
  revealJournal: "Diario configurado para {assets}",
  revealPain: "Empezamos por tu mayor fuga: {pain}",
  revealIct: "Checklist de confluencias ICT / SMC cargada",
  revealLang: "Idioma configurado en {lang}",
  revealBrokers: "Import de {brokers} listo en Ajustes",
  revealCta: "Entrar a TradeVault →",
  revealSaving: "Configurando…",
  yourMarkets: "tus mercados",
  missionCons: "En misión por la consistencia.",
  missionProp: "Cazando el payout.",
  missionFull: "Rumbo a tiempo completo.",
  missionSide: "Un ingreso extra.",
  missionDisc: "Construyendo disciplina.",
};

const pt: OnboardingCopy = {
  langTitle: "Escolha seu idioma",
  langSub: "Todo o app ficará neste idioma.",
  welcomeTitle: "Bem-vindo ao TradeVault",
  welcomeSub:
    "Seu diário de trading, feito para achar seu edge. Registre cada trade, veja o que funciona de verdade e corrija os vazamentos antes que custem caro.",
  feat1T: "Registre cada trade",
  feat1D: "Entradas, saídas, prints, erros — um diário limpo.",
  feat2T: "Veja seu edge real",
  feat2D: "Win rate, R-múltiplos e análises que não mentem.",
  feat3T: "Insights de IA + checklist",
  feat3D: "Ache padrões e trave seu processo antes da abertura.",
  welcomeCta: "Configurar — 30 segundos",
  welcomeSkip: "Pular, vou explorar sozinho",
  cont: "Continuar",
  skip: "Pular",
  skipAdd: "Pular, adiciono depois",
  assetsTitle: "O que você opera?",
  assetsSub: "Escolha tudo que se aplica. Falaremos nas suas unidades.",
  aFutures: "Futuros",
  aForex: "Forex",
  aStocks: "Ações",
  aOptions: "Opções",
  aCrypto: "Cripto",
  styleTitle: "Como você opera?",
  styleSub: "Seu feijão com arroz.",
  sScalper: "Scalper",
  sScalperD: "Entra e sai. Segundos a minutos.",
  sDay: "Day Trader",
  sDayD: "Zerado no fechamento. Sem risco overnight.",
  sSwing: "Swing",
  sSwingD: "Dias a semanas. No movimento maior.",
  sPos: "Posição",
  sPosD: "Semanas a meses. Convicção macro.",
  ictTitle: "Você opera conceitos ICT / SMC?",
  ictSub: "Order blocks, liquidez, FVG, killzones.",
  ictYes: "Sim, sou eu",
  ictNo: "Nem tanto",
  expTitle: "Há quanto tempo nisso?",
  expSub: "Sem julgamento — só ajusta o que mostramos.",
  eNew: "Comecei agora",
  eNewD: "Menos de um ano",
  eInt: "Pegando o ritmo",
  eIntD: "1 a 3 anos",
  eSea: "Experiente",
  eSeaD: "3 anos ou mais",
  eFund: "Financiado / Prop",
  eFundD: "Opero capital alocado",
  goalTitle: "Qual é a missão agora?",
  goalSub: "O verdadeiro motivo de você abrir este diário.",
  gCons: "Ficar consistente",
  gConsD: "Parar de devolver os ganhos.",
  gProp: "Passar num challenge prop",
  gPropD: "Bater a meta, respeitar as regras.",
  gFull: "Viver disso",
  gFullD: "Substituir o salário.",
  gSide: "Renda extra",
  gSideD: "Somar algo, sem estresse.",
  gDisc: "Construir disciplina",
  gDiscD: "Dominar a mente, não só os gráficos.",
  painTitle: "O que mais te custa?",
  painSub: "Seja honesto — é aqui que começamos.",
  pCons: "Consistência",
  pConsD: "Semana verde, semana vermelha, repete.",
  pEmo: "Controle emocional",
  pEmoD: "Revenge trade, FOMO, tilt.",
  pRisk: "Gestão de risco",
  pRiskD: "Um trade destrói o mês.",
  pJour: "Manter o diário",
  pJourD: "Não registro, então não aprendo.",
  pOver: "Overtrading",
  pOverD: "Não consigo ficar parado.",
  brokersTitle: "Onde você executa?",
  brokersSub: "Para importar CSV num toque depois. Sem login — só o nome.",
  revealTitle: "Seu vault está pronto.",
  revealJournal: "Diário configurado para {assets}",
  revealPain: "Vamos começar pelo seu maior vazamento: {pain}",
  revealIct: "Checklist de confluências ICT / SMC carregada",
  revealLang: "Idioma definido para {lang}",
  revealBrokers: "Importação {brokers} pronta nas Configurações",
  revealCta: "Entrar no TradeVault →",
  revealSaving: "Configurando…",
  yourMarkets: "seus mercados",
  missionCons: "Em missão pela consistência.",
  missionProp: "Atrás do payout.",
  missionFull: "Rumo ao tempo integral.",
  missionSide: "Uma renda a mais.",
  missionDisc: "Construindo disciplina.",
};

const de: OnboardingCopy = {
  langTitle: "Wähle deine Sprache",
  langSub: "Die ganze App wird in dieser Sprache sein.",
  welcomeTitle: "Willkommen bei TradeVault",
  welcomeSub:
    "Dein Trading-Journal, gebaut um deinen Edge zu finden. Logge jeden Trade, sieh was wirklich funktioniert und stopfe die Lecks, bevor sie teuer werden.",
  feat1T: "Jeden Trade journalen",
  feat1D: "Entries, Exits, Screenshots, Fehler — ein sauberes Log.",
  feat2T: "Deinen echten Edge sehen",
  feat2D: "Trefferquote, R-Multiples und Analysen, die nicht lügen.",
  feat3T: "KI-Insights + Checkliste",
  feat3D: "Muster erkennen und deinen Prozess vor der Eröffnung fixieren.",
  welcomeCta: "Einrichten — 30 Sekunden",
  welcomeSkip: "Überspringen, ich schau selbst",
  cont: "Weiter",
  skip: "Überspringen",
  skipAdd: "Überspringen, später hinzufügen",
  assetsTitle: "Was tradest du?",
  assetsSub: "Wähle alles Zutreffende. Wir sprechen in deinen Einheiten.",
  aFutures: "Futures",
  aForex: "Forex",
  aStocks: "Aktien",
  aOptions: "Optionen",
  aCrypto: "Krypto",
  styleTitle: "Wie tradest du?",
  styleSub: "Dein Brot-und-Butter-Stil.",
  sScalper: "Scalper",
  sScalperD: "Rein und raus. Sekunden bis Minuten.",
  sDay: "Day Trader",
  sDayD: "Glatt zum Close. Kein Overnight-Risiko.",
  sSwing: "Swing",
  sSwingD: "Tage bis Wochen. Auf der größeren Bewegung.",
  sPos: "Position",
  sPosD: "Wochen bis Monate. Makro-Überzeugung.",
  ictTitle: "Tradest du ICT / SMC Konzepte?",
  ictSub: "Order Blocks, Liquidität, FVGs, Killzones.",
  ictYes: "Ja, das bin ich",
  ictNo: "Eher nicht",
  expTitle: "Wie lange machst du das schon?",
  expSub: "Kein Urteil — das justiert nur, was wir dir zeigen.",
  eNew: "Grade angefangen",
  eNewD: "Unter einem Jahr",
  eInt: "Sammle Reps",
  eIntD: "1–3 Jahre",
  eSea: "Erfahren",
  eSeaD: "3 Jahre+",
  eFund: "Funded / Prop",
  eFundD: "Ich trade zugewiesenes Kapital",
  goalTitle: "Was ist gerade die Mission?",
  goalSub: "Der echte Grund, warum du dieses Journal geöffnet hast.",
  gCons: "Konstant werden",
  gConsD: "Aufhören, Gewinne zurückzugeben.",
  gProp: "Prop-Challenge bestehen",
  gPropD: "Ziel treffen, Regeln einhalten.",
  gFull: "Vollzeit gehen",
  gFullD: "Das Gehalt ersetzen.",
  gSide: "Nebeneinkommen",
  gSideD: "Extra sammeln, wenig Stress.",
  gDisc: "Disziplin aufbauen",
  gDiscD: "Den Kopf meistern, nicht nur die Charts.",
  painTitle: "Was kostet dich am meisten?",
  painSub: "Sei ehrlich — hier fangen wir an.",
  pCons: "Konstanz",
  pConsD: "Grüne Woche, rote Woche, Wiederholung.",
  pEmo: "Emotionskontrolle",
  pEmoD: "Revenge Trades, FOMO, Tilt.",
  pRisk: "Risikomanagement",
  pRiskD: "Ein Trade ruiniert den Monat.",
  pJour: "Journal führen",
  pJourD: "Ich logge nicht, also lerne ich nicht.",
  pOver: "Overtrading",
  pOverD: "Kann nicht stillhalten.",
  brokersTitle: "Wo führst du aus?",
  brokersSub: "Für späteren CSV-Import per Tap. Kein Login — nur der Name.",
  revealTitle: "Dein Vault ist bereit.",
  revealJournal: "Journal eingerichtet für {assets}",
  revealPain: "Wir starten mit deinem größten Leck: {pain}",
  revealIct: "ICT / SMC Konfluenz-Checkliste geladen",
  revealLang: "Sprache auf {lang} gesetzt",
  revealBrokers: "{brokers} Import bereit in den Einstellungen",
  revealCta: "TradeVault betreten →",
  revealSaving: "Wird eingerichtet…",
  yourMarkets: "deine Märkte",
  missionCons: "Auf Mission für Konstanz.",
  missionProp: "Auf der Jagd nach dem Payout.",
  missionFull: "Auf dem Weg zu Vollzeit.",
  missionSide: "Ein Extra-Einkommen.",
  missionDisc: "Disziplin aufbauen.",
};

const it: OnboardingCopy = {
  langTitle: "Scegli la lingua",
  langSub: "Tutta l'app sarà in questa lingua.",
  welcomeTitle: "Benvenuto su TradeVault",
  welcomeSub:
    "Il tuo diario di trading, fatto per trovare il tuo edge. Registra ogni trade, vedi cosa funziona davvero e tappa le falle prima che costino.",
  feat1T: "Registra ogni trade",
  feat1D: "Entrate, uscite, screenshot, errori — un diario pulito.",
  feat2T: "Vedi il tuo vero edge",
  feat2D: "Win rate, R-multipli e analisi che non mentono.",
  feat3T: "Insight IA + checklist",
  feat3D: "Trova i pattern e fissa il tuo processo prima dell'apertura.",
  welcomeCta: "Configura — 30 secondi",
  welcomeSkip: "Salta, esploro da solo",
  cont: "Continua",
  skip: "Salta",
  skipAdd: "Salta, aggiungo dopo",
  assetsTitle: "Cosa tradi?",
  assetsSub: "Scegli tutto ciò che si applica. Parleremo nelle tue unità.",
  aFutures: "Futures",
  aForex: "Forex",
  aStocks: "Azioni",
  aOptions: "Opzioni",
  aCrypto: "Cripto",
  styleTitle: "Come lo tradi?",
  styleSub: "Il tuo pane quotidiano.",
  sScalper: "Scalper",
  sScalperD: "Dentro e fuori. Secondi o minuti.",
  sDay: "Day Trader",
  sDayD: "Flat alla chiusura. Nessun rischio overnight.",
  sSwing: "Swing",
  sSwingD: "Giorni o settimane. Sul movimento maggiore.",
  sPos: "Position",
  sPosD: "Settimane o mesi. Convinzione macro.",
  ictTitle: "Tradi i concetti ICT / SMC?",
  ictSub: "Order block, liquidità, FVG, killzone.",
  ictYes: "Sì, sono io",
  ictNo: "Non proprio",
  expTitle: "Da quanto lo fai?",
  expSub: "Nessun giudizio — regola solo ciò che ti mostriamo.",
  eNew: "Appena iniziato",
  eNewD: "Meno di un anno",
  eInt: "Prendo ritmo",
  eIntD: "1–3 anni",
  eSea: "Esperto",
  eSeaD: "3 anni e oltre",
  eFund: "Funded / Prop",
  eFundD: "Trado capitale allocato",
  goalTitle: "Qual è la missione ora?",
  goalSub: "Il vero motivo per cui hai aperto questo diario.",
  gCons: "Diventare costante",
  gConsD: "Smettere di restituire i profitti.",
  gProp: "Passare una challenge prop",
  gPropD: "Colpire il target, rispettare le regole.",
  gFull: "Fare full-time",
  gFullD: "Sostituire lo stipendio.",
  gSide: "Entrata extra",
  gSideD: "Accumulare extra, poco stress.",
  gDisc: "Costruire disciplina",
  gDiscD: "Dominare la mente, non solo i grafici.",
  painTitle: "Cosa ti costa di più?",
  painSub: "Sii onesto — è da qui che partiamo.",
  pCons: "Costanza",
  pConsD: "Settimana verde, settimana rossa, ripeti.",
  pEmo: "Controllo emotivo",
  pEmoD: "Revenge trade, FOMO, tilt.",
  pRisk: "Gestione del rischio",
  pRiskD: "Un trade rovina il mese.",
  pJour: "Tenere il diario",
  pJourD: "Non registro, quindi non imparo.",
  pOver: "Overtrading",
  pOverD: "Non riesco a stare fermo.",
  brokersTitle: "Dove esegui?",
  brokersSub: "Per import CSV in un tap più tardi. Niente login — solo il nome.",
  revealTitle: "Il tuo vault è pronto.",
  revealJournal: "Diario configurato per {assets}",
  revealPain: "Partiamo dalla tua falla più grande: {pain}",
  revealIct: "Checklist di confluenze ICT / SMC caricata",
  revealLang: "Lingua impostata su {lang}",
  revealBrokers: "Import {brokers} pronto nelle Impostazioni",
  revealCta: "Entra in TradeVault →",
  revealSaving: "Configurazione…",
  yourMarkets: "i tuoi mercati",
  missionCons: "In missione per la costanza.",
  missionProp: "A caccia del payout.",
  missionFull: "Verso il full-time.",
  missionSide: "Un'entrata in più.",
  missionDisc: "Costruire disciplina.",
};

const nl: OnboardingCopy = {
  langTitle: "Kies je taal",
  langSub: "De hele app komt in deze taal.",
  welcomeTitle: "Welkom bij TradeVault",
  welcomeSub:
    "Je trading-journal, gebouwd om je edge te vinden. Log elke trade, zie wat écht werkt en dicht de lekken voor ze je geld kosten.",
  feat1T: "Log elke trade",
  feat1D: "Entries, exits, screenshots, fouten — één schoon logboek.",
  feat2T: "Zie je echte edge",
  feat2D: "Win rate, R-multiples en analyses die niet liegen.",
  feat3T: "AI-inzichten + checklist",
  feat3D: "Herken patronen en zet je proces vast vóór de open.",
  welcomeCta: "Instellen — 30 seconden",
  welcomeSkip: "Overslaan, ik kijk zelf",
  cont: "Doorgaan",
  skip: "Overslaan",
  skipAdd: "Overslaan, later toevoegen",
  assetsTitle: "Wat trade je?",
  assetsSub: "Kies alles wat van toepassing is. We praten in jouw eenheden.",
  aFutures: "Futures",
  aForex: "Forex",
  aStocks: "Aandelen",
  aOptions: "Opties",
  aCrypto: "Crypto",
  styleTitle: "Hoe trade je het?",
  styleSub: "Je dagelijkse brood.",
  sScalper: "Scalper",
  sScalperD: "Erin en eruit. Seconden tot minuten.",
  sDay: "Day Trader",
  sDayD: "Vlak bij de close. Geen overnight-risico.",
  sSwing: "Swing",
  sSwingD: "Dagen tot weken. Op de grotere beweging.",
  sPos: "Positie",
  sPosD: "Weken tot maanden. Macro-overtuiging.",
  ictTitle: "Trade je ICT / SMC concepten?",
  ictSub: "Order blocks, liquiditeit, FVG's, killzones.",
  ictYes: "Ja, dat ben ik",
  ictNo: "Niet echt",
  expTitle: "Hoe lang doe je dit al?",
  expSub: "Geen oordeel — dit stemt alleen af wat we tonen.",
  eNew: "Net begonnen",
  eNewD: "Minder dan een jaar",
  eInt: "Reps aan het maken",
  eIntD: "1–3 jaar",
  eSea: "Ervaren",
  eSeaD: "3 jaar+",
  eFund: "Funded / Prop",
  eFundD: "Ik trade toegewezen kapitaal",
  goalTitle: "Wat is nu de missie?",
  goalSub: "De echte reden dat je dit journal opende.",
  gCons: "Consistent worden",
  gConsD: "Stop met winst teruggeven.",
  gProp: "Een prop-challenge halen",
  gPropD: "Haal het doel, respecteer de regels.",
  gFull: "Fulltime gaan",
  gFullD: "Het salaris vervangen.",
  gSide: "Bijverdienste",
  gSideD: "Extra sparen, weinig stress.",
  gDisc: "Discipline opbouwen",
  gDiscD: "Beheers de geest, niet alleen de charts.",
  painTitle: "Wat kost je het meest?",
  painSub: "Wees eerlijk — hier beginnen we.",
  pCons: "Consistentie",
  pConsD: "Groene week, rode week, herhaal.",
  pEmo: "Emotiecontrole",
  pEmoD: "Revenge trades, FOMO, tilt.",
  pRisk: "Risicobeheer",
  pRiskD: "Eén trade verpest de maand.",
  pJour: "Journal bijhouden",
  pJourD: "Ik log niet, dus ik leer niet.",
  pOver: "Overtrading",
  pOverD: "Kan niet stilzitten.",
  brokersTitle: "Waar voer je uit?",
  brokersSub: "Voor latere CSV-import met één tik. Geen login — alleen de naam.",
  revealTitle: "Je vault is klaar.",
  revealJournal: "Journal ingesteld voor {assets}",
  revealPain: "We beginnen bij je grootste lek: {pain}",
  revealIct: "ICT / SMC confluentie-checklist geladen",
  revealLang: "Taal ingesteld op {lang}",
  revealBrokers: "{brokers} import klaar in Instellingen",
  revealCta: "TradeVault binnengaan →",
  revealSaving: "Instellen…",
  yourMarkets: "jouw markten",
  missionCons: "Op missie voor consistentie.",
  missionProp: "Op jacht naar de payout.",
  missionFull: "Op weg naar fulltime.",
  missionSide: "Een extra inkomen.",
  missionDisc: "Discipline opbouwen.",
};

const ru: OnboardingCopy = {
  langTitle: "Выбери язык",
  langSub: "Всё приложение будет на этом языке.",
  welcomeTitle: "Добро пожаловать в TradeVault",
  welcomeSub:
    "Твой торговый журнал, чтобы найти своё преимущество. Записывай каждую сделку, смотри что реально работает и закрывай утечки, пока они не стоили дорого.",
  feat1T: "Записывай каждую сделку",
  feat1D: "Входы, выходы, скриншоты, ошибки — один чистый журнал.",
  feat2T: "Увидь своё реальное преимущество",
  feat2D: "Винрейт, R-мультипликаторы и честная аналитика.",
  feat3T: "ИИ-инсайты + чек-лист",
  feat3D: "Находи паттерны и фиксируй процесс до открытия.",
  welcomeCta: "Настроить — 30 секунд",
  welcomeSkip: "Пропустить, разберусь сам",
  cont: "Продолжить",
  skip: "Пропустить",
  skipAdd: "Пропустить, добавлю позже",
  assetsTitle: "Чем ты торгуешь?",
  assetsSub: "Выбери всё подходящее. Будем говорить в твоих единицах.",
  aFutures: "Фьючерсы",
  aForex: "Форекс",
  aStocks: "Акции",
  aOptions: "Опционы",
  aCrypto: "Крипта",
  styleTitle: "Как ты торгуешь?",
  styleSub: "Твой основной стиль.",
  sScalper: "Скальпер",
  sScalperD: "Вошёл-вышел. Секунды-минуты.",
  sDay: "Дейтрейдер",
  sDayD: "К закрытию без позиций. Без риска овернайт.",
  sSwing: "Свинг",
  sSwingD: "Дни-недели. На крупном движении.",
  sPos: "Позиционный",
  sPosD: "Недели-месяцы. Макро-убеждённость.",
  ictTitle: "Торгуешь по ICT / SMC?",
  ictSub: "Order blocks, ликвидность, FVG, killzones.",
  ictYes: "Да, это про меня",
  ictNo: "Не особо",
  expTitle: "Сколько ты в этом?",
  expSub: "Без осуждения — это лишь настроит, что тебе показать.",
  eNew: "Только начал",
  eNewD: "Меньше года",
  eInt: "Набираю опыт",
  eIntD: "1–3 года",
  eSea: "Опытный",
  eSeaD: "3 года и больше",
  eFund: "Funded / Prop",
  eFundD: "Торгую выделенный капитал",
  goalTitle: "Какая сейчас цель?",
  goalSub: "Настоящая причина, почему ты открыл этот журнал.",
  gCons: "Стать стабильным",
  gConsD: "Перестать отдавать прибыль.",
  gProp: "Пройти prop-челлендж",
  gPropD: "Достичь цели, соблюсти правила.",
  gFull: "Уйти в фултайм",
  gFullD: "Заменить зарплату.",
  gSide: "Доп. доход",
  gSideD: "Добавить сверху, без стресса.",
  gDisc: "Построить дисциплину",
  gDiscD: "Освоить ум, а не только графики.",
  painTitle: "Что стоит тебе дороже всего?",
  painSub: "Честно — отсюда и начнём.",
  pCons: "Стабильность",
  pConsD: "Зелёная неделя, красная неделя, по кругу.",
  pEmo: "Контроль эмоций",
  pEmoD: "Отыгрыш, FOMO, тильт.",
  pRisk: "Риск-менеджмент",
  pRiskD: "Одна сделка убивает месяц.",
  pJour: "Ведение журнала",
  pJourD: "Не записываю — значит не учусь.",
  pOver: "Овертрейдинг",
  pOverD: "Не могу сидеть на руках.",
  brokersTitle: "Где исполняешь?",
  brokersSub: "Для импорта CSV в один тап потом. Без логина — только название.",
  revealTitle: "Твой vault готов.",
  revealJournal: "Журнал настроен под {assets}",
  revealPain: "Начнём с твоей главной утечки: {pain}",
  revealIct: "Чек-лист конфлюэнсов ICT / SMC загружен",
  revealLang: "Язык установлен: {lang}",
  revealBrokers: "Импорт {brokers} готов в Настройках",
  revealCta: "Войти в TradeVault →",
  revealSaving: "Настройка…",
  yourMarkets: "твои рынки",
  missionCons: "На пути к стабильности.",
  missionProp: "В погоне за выплатой.",
  missionFull: "Курс на фултайм.",
  missionSide: "Доход сверху.",
  missionDisc: "Строим дисциплину.",
};

const zh: OnboardingCopy = {
  langTitle: "选择你的语言",
  langSub: "整个应用将使用这种语言。",
  welcomeTitle: "欢迎来到 TradeVault",
  welcomeSub:
    "你的交易日志，专为找到你的优势而生。记录每一笔交易，看清什么真正有效，在漏洞变贵之前补上它。",
  feat1T: "记录每一笔交易",
  feat1D: "入场、出场、截图、错误——一份干净的记录。",
  feat2T: "看清你真正的优势",
  feat2D: "胜率、R 倍数，以及不会骗人的分析。",
  feat3T: "AI 洞察 + 清单",
  feat3D: "发现规律，在开盘前锁定你的流程。",
  welcomeCta: "开始设置——30 秒",
  welcomeSkip: "跳过，我自己探索",
  cont: "继续",
  skip: "跳过",
  skipAdd: "跳过，稍后添加",
  assetsTitle: "你交易什么？",
  assetsSub: "选择所有适用项。我们会用你的单位来沟通。",
  aFutures: "期货",
  aForex: "外汇",
  aStocks: "股票",
  aOptions: "期权",
  aCrypto: "加密货币",
  styleTitle: "你怎么交易？",
  styleSub: "你的看家本领。",
  sScalper: "剥头皮",
  sScalperD: "快进快出。几秒到几分钟。",
  sDay: "日内交易者",
  sDayD: "收盘前平仓。无隔夜风险。",
  sSwing: "波段",
  sSwingD: "几天到几周。抓更大的行情。",
  sPos: "头寸",
  sPosD: "几周到几月。宏观信念。",
  ictTitle: "你交易 ICT / SMC 概念吗？",
  ictSub: "订单块、流动性、FVG、killzone。",
  ictYes: "是的，就是我",
  ictNo: "不太算",
  expTitle: "你做多久了？",
  expSub: "没有评判——这只是调整我们给你展示的内容。",
  eNew: "刚起步",
  eNewD: "不到一年",
  eInt: "正在积累",
  eIntD: "1–3 年",
  eSea: "老手",
  eSeaD: "3 年以上",
  eFund: "受资 / Prop",
  eFundD: "交易分配的资金",
  goalTitle: "现在的目标是什么？",
  goalSub: "你打开这个日志的真正原因。",
  gCons: "变得稳定",
  gConsD: "别再把利润还回去。",
  gProp: "通过 prop 挑战",
  gPropD: "达成目标，遵守规则。",
  gFull: "转为全职",
  gFullD: "取代工资。",
  gSide: "副业收入",
  gSideD: "多赚一点，压力小。",
  gDisc: "建立纪律",
  gDiscD: "掌控心态，而不只是图表。",
  painTitle: "什么让你损失最大？",
  painSub: "说实话——我们从这里开始。",
  pCons: "稳定性",
  pConsD: "绿一周，红一周，反复循环。",
  pEmo: "情绪控制",
  pEmoD: "报复性交易、FOMO、上头。",
  pRisk: "风险管理",
  pRiskD: "一笔交易毁掉一个月。",
  pJour: "记录日志",
  pJourD: "不记录，所以学不到东西。",
  pOver: "过度交易",
  pOverD: "闲不住手。",
  brokersTitle: "你在哪里执行？",
  brokersSub: "方便以后一键导入 CSV。现在不用登录——只要名字。",
  revealTitle: "你的 vault 已就绪。",
  revealJournal: "日志已为 {assets} 配置好",
  revealPain: "我们先从你最大的漏洞开始：{pain}",
  revealIct: "ICT / SMC 汇合清单已加载",
  revealLang: "语言已设为 {lang}",
  revealBrokers: "{brokers} 导入已在设置中就绪",
  revealCta: "进入 TradeVault →",
  revealSaving: "正在设置…",
  yourMarkets: "你的市场",
  missionCons: "为稳定而战。",
  missionProp: "追逐分成。",
  missionFull: "迈向全职。",
  missionSide: "多一份收入。",
  missionDisc: "建立纪律。",
};

const ja: OnboardingCopy = {
  langTitle: "言語を選ぶ",
  langSub: "アプリ全体がこの言語になります。",
  welcomeTitle: "TradeVault へようこそ",
  welcomeSub:
    "あなたのエッジを見つけるためのトレード日誌。すべてのトレードを記録し、本当に効いているものを見極め、コストになる前に穴を塞ぐ。",
  feat1T: "全トレードを記録",
  feat1D: "エントリー、エグジット、スクショ、ミス——一つのきれいなログ。",
  feat2T: "本当のエッジを見る",
  feat2D: "勝率、R倍率、嘘をつかない分析。",
  feat3T: "AIインサイト + チェックリスト",
  feat3D: "パターンを見つけ、寄り付き前にプロセスを固める。",
  welcomeCta: "設定する——30秒",
  welcomeSkip: "スキップ、自分で見る",
  cont: "続ける",
  skip: "スキップ",
  skipAdd: "スキップ、後で追加",
  assetsTitle: "何をトレードする？",
  assetsSub: "該当するものをすべて選択。あなたの単位で話します。",
  aFutures: "先物",
  aForex: "FX",
  aStocks: "株式",
  aOptions: "オプション",
  aCrypto: "暗号資産",
  styleTitle: "どうトレードする？",
  styleSub: "あなたの得意技。",
  sScalper: "スキャルパー",
  sScalperD: "入って出る。数秒〜数分。",
  sDay: "デイトレーダー",
  sDayD: "引けまでにフラット。オーバーナイトなし。",
  sSwing: "スイング",
  sSwingD: "数日〜数週間。大きな動きに乗る。",
  sPos: "ポジション",
  sPosD: "数週間〜数ヶ月。マクロの確信。",
  ictTitle: "ICT / SMC を使う？",
  ictSub: "オーダーブロック、流動性、FVG、キルゾーン。",
  ictYes: "はい、まさに",
  ictNo: "あまり",
  expTitle: "どれくらいやってる？",
  expSub: "評価はしません——表示内容を調整するだけ。",
  eNew: "始めたばかり",
  eNewD: "1年未満",
  eInt: "経験を積み中",
  eIntD: "1〜3年",
  eSea: "熟練",
  eSeaD: "3年以上",
  eFund: "ファンデッド / Prop",
  eFundD: "割り当て資金でトレード",
  goalTitle: "今のミッションは？",
  goalSub: "この日誌を開いた本当の理由。",
  gCons: "安定する",
  gConsD: "勝ち分を返すのをやめる。",
  gProp: "propチャレンジ突破",
  gPropD: "目標達成、ルール順守。",
  gFull: "専業になる",
  gFullD: "給料を置き換える。",
  gSide: "副収入",
  gSideD: "少し上乗せ、低ストレス。",
  gDisc: "規律を築く",
  gDiscD: "チャートだけでなくメンタルを制す。",
  painTitle: "一番コストになっているのは？",
  painSub: "正直に——ここから始めます。",
  pCons: "一貫性",
  pConsD: "勝ち週、負け週、繰り返し。",
  pEmo: "感情のコントロール",
  pEmoD: "リベンジトレード、FOMO、ティルト。",
  pRisk: "リスク管理",
  pRiskD: "1トレードで月をぶち壊す。",
  pJour: "日誌をつける",
  pJourD: "記録しないから学べない。",
  pOver: "オーバートレード",
  pOverD: "手を止められない。",
  brokersTitle: "どこで執行する？",
  brokersSub: "後でCSVをワンタップ取込するため。ログイン不要——名前だけ。",
  revealTitle: "あなたの vault が準備完了。",
  revealJournal: "{assets} 向けに日誌を設定",
  revealPain: "まずは一番の穴から：{pain}",
  revealIct: "ICT / SMC コンフルエンスのチェックリストを読込",
  revealLang: "言語を {lang} に設定",
  revealBrokers: "{brokers} の取込を設定に用意",
  revealCta: "TradeVault に入る →",
  revealSaving: "設定中…",
  yourMarkets: "あなたの市場",
  missionCons: "一貫性を目指して。",
  missionProp: "ペイアウトを狙う。",
  missionFull: "専業へ。",
  missionSide: "副収入を上乗せ。",
  missionDisc: "規律を築く。",
};

const ar: OnboardingCopy = {
  langTitle: "اختر لغتك",
  langSub: "سيكون التطبيق بالكامل بهذه اللغة.",
  welcomeTitle: "مرحبًا بك في TradeVault",
  welcomeSub:
    "مذكرة تداولك، مصمّمة لإيجاد ميزتك. سجّل كل صفقة، وشاهد ما ينجح فعلًا، وأغلق الثغرات قبل أن تكلّفك.",
  feat1T: "سجّل كل صفقة",
  feat1D: "الدخول، الخروج، لقطات الشاشة، الأخطاء — سجل واحد نظيف.",
  feat2T: "شاهد ميزتك الحقيقية",
  feat2D: "معدل الربح، مضاعفات R، وتحليلات لا تكذب.",
  feat3T: "رؤى الذكاء الاصطناعي + قائمة",
  feat3D: "اكتشف الأنماط وثبّت خطتك قبل الافتتاح.",
  welcomeCta: "الإعداد — 30 ثانية",
  welcomeSkip: "تخطٍّ، سأستكشف بنفسي",
  cont: "متابعة",
  skip: "تخطٍّ",
  skipAdd: "تخطٍّ، سأضيف لاحقًا",
  assetsTitle: "ماذا تتداول؟",
  assetsSub: "اختر كل ما ينطبق. سنتحدث بوحداتك.",
  aFutures: "العقود الآجلة",
  aForex: "الفوركس",
  aStocks: "الأسهم",
  aOptions: "الخيارات",
  aCrypto: "الكريبتو",
  styleTitle: "كيف تتداولها؟",
  styleSub: "أسلوبك الأساسي.",
  sScalper: "مضارب سريع",
  sScalperD: "دخول وخروج. ثوانٍ إلى دقائق.",
  sDay: "متداول يومي",
  sDayD: "بلا مراكز عند الإغلاق. لا مخاطر ليلية.",
  sSwing: "سوينغ",
  sSwingD: "أيام إلى أسابيع. على الحركة الأكبر.",
  sPos: "مراكز",
  sPosD: "أسابيع إلى أشهر. قناعة كلية.",
  ictTitle: "هل تتداول مفاهيم ICT / SMC؟",
  ictSub: "أوردر بلوك، السيولة، FVG، الكيل زون.",
  ictYes: "نعم، هذا أنا",
  ictNo: "ليس تمامًا",
  expTitle: "منذ متى وأنت في هذا؟",
  expSub: "بلا أحكام — هذا فقط يضبط ما نعرضه لك.",
  eNew: "بدأت للتو",
  eNewD: "أقل من سنة",
  eInt: "أكتسب خبرة",
  eIntD: "1–3 سنوات",
  eSea: "محترف",
  eSeaD: "3 سنوات فأكثر",
  eFund: "ممول / Prop",
  eFundD: "أتداول رأس مال مخصّص",
  goalTitle: "ما المهمة الآن؟",
  goalSub: "السبب الحقيقي لفتحك هذه المذكرة.",
  gCons: "أصبح ثابتًا",
  gConsD: "توقف عن إعادة الأرباح.",
  gProp: "اجتياز تحدي prop",
  gPropD: "حقّق الهدف، احترم القواعد.",
  gFull: "التفرّغ الكامل",
  gFullD: "استبدال الراتب.",
  gSide: "دخل إضافي",
  gSideD: "أضف قليلًا، بضغط أقل.",
  gDisc: "بناء الانضباط",
  gDiscD: "أتقن العقل، لا الرسوم فقط.",
  painTitle: "ما الذي يكلّفك أكثر؟",
  painSub: "كن صادقًا — من هنا نبدأ.",
  pCons: "الثبات",
  pConsD: "أسبوع أخضر، أسبوع أحمر، وتكرار.",
  pEmo: "التحكم العاطفي",
  pEmoD: "صفقات انتقامية، FOMO، تيلت.",
  pRisk: "إدارة المخاطر",
  pRiskD: "صفقة واحدة تدمّر الشهر.",
  pJour: "تدوين المذكرة",
  pJourD: "لا أسجّل، فلا أتعلّم.",
  pOver: "الإفراط في التداول",
  pOverD: "لا أستطيع الجلوس مكتوف اليدين.",
  brokersTitle: "أين تنفّذ؟",
  brokersSub: "لاستيراد CSV بنقرة لاحقًا. بلا تسجيل دخول — الاسم فقط.",
  revealTitle: "خزنتك جاهزة.",
  revealJournal: "تم إعداد المذكرة لـ {assets}",
  revealPain: "سنبدأ بأكبر ثغرة لديك: {pain}",
  revealIct: "تم تحميل قائمة تقاطعات ICT / SMC",
  revealLang: "تم ضبط اللغة على {lang}",
  revealBrokers: "استيراد {brokers} جاهز في الإعدادات",
  revealCta: "ادخل TradeVault →",
  revealSaving: "جارٍ الإعداد…",
  yourMarkets: "أسواقك",
  missionCons: "في مهمة نحو الثبات.",
  missionProp: "سعيًا وراء الدفع.",
  missionFull: "نحو التفرّغ الكامل.",
  missionSide: "دخل إضافي.",
  missionDisc: "بناء الانضباط.",
};

const hi: OnboardingCopy = {
  langTitle: "अपनी भाषा चुनें",
  langSub: "पूरा ऐप इसी भाषा में होगा।",
  welcomeTitle: "TradeVault में आपका स्वागत है",
  welcomeSub:
    "आपका ट्रेडिंग जर्नल, आपकी एज ढूँढने के लिए बना। हर ट्रेड लॉग करें, देखें क्या वाकई काम करता है, और लीक महँगे पड़ने से पहले भरें।",
  feat1T: "हर ट्रेड लॉग करें",
  feat1D: "एंट्री, एग्ज़िट, स्क्रीनशॉट, गलतियाँ — एक साफ़ लॉग।",
  feat2T: "अपनी असली एज देखें",
  feat2D: "विन रेट, R-मल्टिपल्स और झूठ न बोलने वाला एनालिटिक्स।",
  feat3T: "AI इनसाइट्स + चेकलिस्ट",
  feat3D: "पैटर्न पकड़ें और ओपन से पहले अपना प्रोसेस लॉक करें।",
  welcomeCta: "सेट करें — 30 सेकंड",
  welcomeSkip: "छोड़ें, मैं खुद देख लूँगा",
  cont: "जारी रखें",
  skip: "छोड़ें",
  skipAdd: "छोड़ें, बाद में जोड़ूँगा",
  assetsTitle: "आप क्या ट्रेड करते हैं?",
  assetsSub: "जो लागू हो सब चुनें। हम आपकी इकाइयों में बात करेंगे।",
  aFutures: "फ्यूचर्स",
  aForex: "फॉरेक्स",
  aStocks: "स्टॉक्स",
  aOptions: "ऑप्शन्स",
  aCrypto: "क्रिप्टो",
  styleTitle: "आप इसे कैसे ट्रेड करते हैं?",
  styleSub: "आपका मुख्य तरीका।",
  sScalper: "स्कैल्पर",
  sScalperD: "अंदर और बाहर। सेकंड से मिनट।",
  sDay: "डे ट्रेडर",
  sDayD: "क्लोज़ तक फ्लैट। कोई ओवरनाइट रिस्क नहीं।",
  sSwing: "स्विंग",
  sSwingD: "दिन से हफ्ते। बड़े मूव पर।",
  sPos: "पोज़िशन",
  sPosD: "हफ्ते से महीने। मैक्रो भरोसा।",
  ictTitle: "क्या आप ICT / SMC कॉन्सेप्ट ट्रेड करते हैं?",
  ictSub: "ऑर्डर ब्लॉक, लिक्विडिटी, FVG, किलज़ोन।",
  ictYes: "हाँ, बिल्कुल मैं",
  ictNo: "ज़्यादा नहीं",
  expTitle: "आप कब से यह कर रहे हैं?",
  expSub: "कोई जजमेंट नहीं — यह बस तय करता है कि हम क्या दिखाएँ।",
  eNew: "अभी शुरू किया",
  eNewD: "एक साल से कम",
  eInt: "अनुभव बढ़ा रहा हूँ",
  eIntD: "1–3 साल",
  eSea: "अनुभवी",
  eSeaD: "3 साल+",
  eFund: "फंडेड / Prop",
  eFundD: "आवंटित पूँजी ट्रेड करता हूँ",
  goalTitle: "अभी मिशन क्या है?",
  goalSub: "इस जर्नल को खोलने की असली वजह।",
  gCons: "निरंतर बनना",
  gConsD: "मुनाफ़ा वापस देना बंद करें।",
  gProp: "prop चैलेंज पास करना",
  gPropD: "टारगेट हिट करें, नियम मानें।",
  gFull: "फुल-टाइम जाना",
  gFullD: "तनख्वाह की जगह लेना।",
  gSide: "साइड इनकम",
  gSideD: "थोड़ा अतिरिक्त, कम तनाव।",
  gDisc: "अनुशासन बनाना",
  gDiscD: "सिर्फ़ चार्ट नहीं, दिमाग पर काबू।",
  painTitle: "सबसे ज़्यादा किस चीज़ की कीमत चुका रहे हैं?",
  painSub: "ईमानदार रहें — यहीं से शुरू करते हैं।",
  pCons: "निरंतरता",
  pConsD: "हरा हफ्ता, लाल हफ्ता, दोहराव।",
  pEmo: "भावनाओं पर नियंत्रण",
  pEmoD: "रिवेंज ट्रेड, FOMO, टिल्ट।",
  pRisk: "रिस्क मैनेजमेंट",
  pRiskD: "एक ट्रेड पूरा महीना बिगाड़ देता है।",
  pJour: "जर्नल रखना",
  pJourD: "लॉग नहीं करता, तो सीखता नहीं।",
  pOver: "ओवरट्रेडिंग",
  pOverD: "हाथ पर हाथ धरे नहीं बैठ सकता।",
  brokersTitle: "आप कहाँ एग्ज़िक्यूट करते हैं?",
  brokersSub: "बाद में एक-टैप CSV इम्पोर्ट के लिए। अभी लॉगिन नहीं — बस नाम।",
  revealTitle: "आपका vault तैयार है।",
  revealJournal: "{assets} के लिए जर्नल सेट हो गया",
  revealPain: "हम आपकी सबसे बड़ी लीक से शुरू करेंगे: {pain}",
  revealIct: "ICT / SMC कॉन्फ्लुएंस चेकलिस्ट लोड हुई",
  revealLang: "भाषा {lang} पर सेट",
  revealBrokers: "{brokers} इम्पोर्ट सेटिंग्स में तैयार",
  revealCta: "TradeVault में जाएँ →",
  revealSaving: "सेट हो रहा है…",
  yourMarkets: "आपके बाज़ार",
  missionCons: "निरंतरता के मिशन पर।",
  missionProp: "पेआउट की तलाश में।",
  missionFull: "फुल-टाइम की ओर।",
  missionSide: "एक अतिरिक्त आय।",
  missionDisc: "अनुशासन बनाना।",
};

const ALL: Record<Lang, OnboardingCopy> = { en, fr, es, pt, de, it, nl, ru, zh, ja, ar, hi };

export function oc(lang: Lang): Required<OnboardingCopy> {
  // `en` defines every key (including the optional quick-start ones), so the
  // merged object is always complete — locales only override what they have.
  return { ...en, ...ALL[lang] } as Required<OnboardingCopy>;
}

/** Fills {placeholder} tokens. */
export function fmt(tpl: string, vars: Record<string, string>): string {
  return tpl.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}
