import { LayoutDashboard, BookOpen, Calendar, BarChart3, AlertTriangle, LogOut, User, Sparkles, Target, ClipboardList, FileText, Palette, CreditCard } from 'lucide-react';
import { Page } from '../types';
import { formatPnl, formatPct } from '../utils/tradeCalcs';
import { useAuth } from '../contexts/AuthContext';
import { useT } from '../i18n/LanguageContext';
import { cn } from '@/lib/utils';
const primary = [{ id: 'dashboard', icon: LayoutDashboard, key: 'nav.dashboard' }, { id: 'journal', icon: BookOpen, key: 'nav.journal' }, { id: 'calendar', icon: Calendar, key: 'nav.calendar' }, { id: 'analytics', icon: BarChart3, key: 'nav.analytics' }, { id: 'mistakes', icon: AlertTriangle, key: 'nav.mistakes' }, { id: 'missed', icon: Target, key: 'nav.missed' }, { id: 'insights', icon: Sparkles, key: 'nav.insights' }];
const planning = [{ id: 'goals', icon: Target, key: 'nav.goals' }, { id: 'trading-plan', icon: ClipboardList, key: 'nav.tradingPlan' }, { id: 'monthly-reports', icon: FileText, key: 'nav.monthlyReports' }];
const account = [{ id: 'appearance', icon: Palette, key: 'nav.appearance' }, { id: 'subscription', icon: CreditCard, key: 'nav.subscription' }, { id: 'profile', icon: User, key: 'nav.profile' }];
export default function Sidebar({ page, setPage, totalPnl, winRate }: { page: Page; setPage: (page: Page) => void; totalPnl: number; winRate: number }) { const { signOut } = useAuth(); const { t } = useT(); const item = (entry: any) => <button key={entry.id} onClick={() => setPage(entry.id)} className={cn('flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left text-sm transition', page === entry.id ? 'bg-cyan-400/10 text-cyan-200' : 'text-slate-400 hover:bg-white/[0.04] hover:text-white')}><entry.icon className="h-4 w-4" />{t(entry.key)}</button>; return <aside className="hidden min-h-screen w-64 shrink-0 border-r border-white/[0.08] bg-slate-950/80 p-4 lg:block"><div className="mb-7 flex items-center gap-3 px-2"><img src="/tradevault-logo.png" className="h-8 w-8 rounded-lg" /><div><p className="font-bold text-white">TradeVault</p><p className="text-[10px] uppercase tracking-widest text-cyan-400">Trading intelligence</p></div></div><div className="space-y-6"><div><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">Workspace</p>{primary.map(item)}</div><div><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">Planning</p>{planning.map(item)}</div><div><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">Account</p>{account.map(item)}</div></div><div className="mt-8 rounded-2xl border border-cyan-300/10 bg-cyan-300/[0.04] p-3"><div className="flex justify-between text-xs text-slate-500"><span>{t('stats.totalPnl')}</span><span className={totalPnl >= 0 ? 'text-emerald-300' : 'text-rose-300'}>{formatPnl(totalPnl)}</span></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{t('stats.winRate')}</span><span className="text-white">{formatPct(winRate)}</span></div></div><button onClick={() => signOut()} className="mt-5 flex items-center gap-3 px-3 py-2 text-sm text-slate-500 hover:text-white"><LogOut className="h-4 w-4" />{t('nav.signOut')}</button></aside>; }
