import { useEffect, useState } from 'react';
import { Check, Moon, Palette, Sparkles, Sun } from 'lucide-react';
import { loadAppearance, saveAppearance } from '../store';
import { LANGUAGES } from '../types';
import { useT } from '../i18n/LanguageContext';
import { useLanguage } from '../i18n/LanguageContext';

const models = [{ id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', detail: 'Balanced reasoning and fast journal insights' }, { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna', detail: 'Deep analysis and structured reports' }, { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', detail: 'Long context for large trade histories' }];
export default function Appearance() {
  const { t } = useT(); const { lang, setLang } = useLanguage(); const [prefs, setPrefs] = useState(() => loadAppearance());
  useEffect(() => { saveAppearance(prefs); document.documentElement.dataset.theme = prefs.theme; }, [prefs]);
  return <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-10 space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-400">TradeVault / Settings</p><h1 className="mt-2 text-3xl font-bold text-white">{t('nav.appearance')}</h1><p className="mt-2 text-sm text-slate-400">Make the workspace feel like yours. Every preference is saved locally.</p></div><section className="glass-strong rounded-3xl p-5 md:p-6"><div className="flex items-center gap-2"><Palette className="h-4 w-4 text-cyan-300" /><h2 className="text-sm font-bold uppercase tracking-wider text-white">Theme</h2></div><div className="mt-4 flex gap-2"><button onClick={() => setPrefs({ ...prefs, theme: 'dark' })} className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-sm ${prefs.theme === 'dark' ? 'border-cyan-300 bg-cyan-300/10 text-cyan-100' : 'border-white/10 text-slate-400'}`}><Moon className="h-4 w-4" />Dark</button><button onClick={() => setPrefs({ ...prefs, theme: 'light' })} className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-sm ${prefs.theme === 'light' ? 'border-cyan-300 bg-cyan-300/10 text-cyan-100' : 'border-white/10 text-slate-400'}`}><Sun className="h-4 w-4" />Light</button></div></section><section className="glass-strong rounded-3xl p-5 md:p-6"><h2 className="text-sm font-bold uppercase tracking-wider text-white">Language</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 md:grid-cols-3">{LANGUAGES.map((item) => <button key={item.code} onClick={() => setLang(item.code)} className={`flex items-center justify-between rounded-xl border px-3 py-3 text-sm ${lang === item.code ? 'border-cyan-300 bg-cyan-300/10 text-white' : 'border-white/10 text-slate-400'}`}>{item.label}{lang === item.code && <Check className="h-4 w-4 text-cyan-300" />}</button>)}</div></section><section className="glass-strong rounded-3xl p-5 md:p-6"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-cyan-300" /><h2 className="text-sm font-bold uppercase tracking-wider text-white">AI model</h2></div><div className="mt-4 space-y-2">{models.map((model) => <button key={model.id} onClick={() => setPrefs({ ...prefs, aiModel: model.id })} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left ${prefs.aiModel === model.id ? 'border-cyan-300 bg-cyan-300/[0.08]' : 'border-white/[0.08] bg-white/[0.025]'}`}><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${prefs.aiModel === model.id ? 'border-cyan-300 bg-cyan-300 text-slate-950' : 'border-white/20'}`}>{prefs.aiModel === model.id && <Check className="h-3 w-3" />}</span><span><span className="block text-sm font-semibold text-white">{model.name}</span><span className="mt-1 block text-xs text-slate-500">{model.detail}</span></span></button>)}</div></section></div>;
}
